defaults: &defaults
  :voter_registration_deadline: 2013-12-2

production:
  <<: *defaults
  :default_host: www.voteabroad.ly

development:
  <<: *defaults
  :default_host: www.votely.dev

test:
  <<: *defaults
  :default_host: www.votely.dev
