defaults: &defaults
  :voter_registration_deadline: 2014-02-11

production:
  <<: *defaults
  :default_host: voteabroad.ly

development:
  <<: *defaults
  :default_host: votely.dev

test:
  <<: *defaults
  :default_host: votely.dev
